name: CV
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - _tflow_select=2.3.0=mkl
  - abseil-cpp=20210324.2=h9c3ff4c_0
  - absl-py=0.15.0=pyhd8ed1ab_0
  - aiohttp=3.7.4.post0=py39h3811e60_0
  - alsa-lib=1.2.3=h516909a_0
  - anyio=3.3.4=py39hf3d152e_1
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=20.1.0=py39h27cfd23_1
  - astor=0.8.1=pyh9f0ad1d_0
  - astroid=2.5.8=py39hf3d152e_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=3.0.1=py_1000
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - audioread=2.1.9=py39hf3d152e_1
  - babel=2.9.1=pyh44b312d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd8ed1ab_0
  - blinker=1.4=py_1
  - brotli=1.0.9=h9c3ff4c_4
  - brotlipy=0.7.0=py39h3811e60_1001
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2021.10.8=ha878542_0
  - cached-property=1.5.2=py_0
  - cachetools=4.2.4=pyhd8ed1ab_0
  - cairo=1.16.0=h6cf1ce9_1008
  - catboost=1.0.3=py39hf3d152e_1
  - certifi=2021.10.8=py39hf3d152e_1
  - cffi=1.14.5=py39h261ae71_0
  - chardet=4.0.0=py39hf3d152e_2
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=35.0.0=py39hbca0aa6_0
  - cudatoolkit=10.2.89=h8f6ccaa_8
  - cudnn=7.6.5.32=h01f27c4_1
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dbus=1.13.6=he372182_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - descartes=1.1.0=py_4
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.4.1=h9c3ff4c_0
  - ffmpeg=4.3.2=hca11adc_0
  - fontconfig=2.13.1=hba837de_1005
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=h0708190_1
  - gast=0.4.0=pyh9f0ad1d_0
  - gettext=0.19.8.1=h0b5b191_1005
  - giflib=5.2.1=h7b6447c_0
  - glib=2.68.4=h9c3ff4c_0
  - glib-tools=2.68.4=h9c3ff4c_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - google-auth=2.3.3=pyh6c4a22f_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyh8c360ce_0
  - graphite2=1.3.13=h58526e2_1001
  - grpc-cpp=1.39.1=h850795e_1
  - grpcio=1.39.0=py39hff7568b_0
  - gst-plugins-base=1.18.5=hf529b03_0
  - gstreamer=1.18.5=h76c114f_0
  - harfbuzz=2.9.1=h83ec7ef_1
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - icu=68.2=h9c3ff4c_0
  - idna=3.1=pyhd3deb0d_0
  - importlib-metadata=4.8.2=py39hf3d152e_0
  - importlib_resources=5.4.0=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=5.5.5=py39hef51801_0
  - ipympl=0.8.5=pyhd8ed1ab_0
  - ipython=7.29.0=py39hef51801_2
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.5=pyhd8ed1ab_0
  - isort=5.10.1=pyhd8ed1ab_0
  - jasper=1.900.1=h07fcdf6_1006
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.0=py39hf3d152e_3
  - jinja2=3.0.3=pyhd8ed1ab_0
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.2.1=pyhd8ed1ab_0
  - jupyter_core=4.9.1=py39hf3d152e_1
  - jupyter_server=1.11.2=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.8.2=pyhd8ed1ab_0
  - jupyterlab_widgets=1.0.2=pyhd8ed1ab_0
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - kiwisolver=1.3.1=py39h2531618_0
  - krb5=1.19.2=hcc1bbae_0
  - lame=3.100=h7f98852_1001
  - lazy-object-proxy=1.6.0=py39h3811e60_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - lerc=2.2.1=h9c3ff4c_0
  - libblas=3.9.0=12_linux64_mkl
  - libcblas=3.9.0=12_linux64_mkl
  - libcurl=7.80.0=h2574ce0_0
  - libdeflate=1.7=h7f98852_5
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.3=he6710b0_2
  - libflac=1.3.3=h9c3ff4c_1
  - libgcc-ng=11.2.0=h1d223b6_11
  - libgfortran-ng=11.2.0=h69a702a_11
  - libgfortran5=11.2.0=h5c6108e_11
  - libglib=2.68.4=h3e27bee_0
  - libgomp=11.2.0=h1d223b6_11
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=12_linux64_mkl
  - liblapacke=3.9.0=12_linux64_mkl
  - libllvm10=10.0.1=he513fc3_3
  - libllvm11=11.1.0=hf817b99_2
  - libnghttp2=1.43.0=h812cca2_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.17=pthreads_h8fe5266_1
  - libopencv=4.5.2=py39h70bf20d_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libpq=13.5=hd57d9b9_1
  - libprotobuf=3.16.0=h780b84a_0
  - librosa=0.8.1=pyhd8ed1ab_0
  - libsndfile=1.0.31=h9c3ff4c_1
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libtiff=4.3.0=hf544144_1
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.42.0=h7f98852_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.13=h7f98852_1003
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - libzlib=1.2.11=h36c2ea0_1013
  - llvmlite=0.36.0=py39h612dafd_4
  - lz4-c=1.9.3=h9c3ff4c_1
  - markdown=3.3.4=pyhd8ed1ab_0
  - markupsafe=2.0.1=py39h3811e60_0
  - matplotlib=3.4.3=py39hf3d152e_2
  - matplotlib-base=3.4.3=py39hbbc1b5f_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mccabe=0.6.1=py_1
  - mistune=0.8.4=py39h3811e60_1004
  - mizani=0.7.3=pyhd8ed1ab_0
  - mkl=2021.4.0=h06a4308_640
  - multidict=5.1.0=py39h3811e60_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.27=ha770c72_3
  - mysql-libs=8.0.27=hfa10184_3
  - nbclassic=0.3.4=pyhd8ed1ab_0
  - nbclient=0.5.8=pyhd8ed1ab_0
  - nbconvert=6.3.0=py39hf3d152e_1
  - nbformat=5.1.3=pyhd8ed1ab_0
  - nccl=2.11.4.1=h1a5f58c_0
  - ncurses=6.3=h7f8727e_2
  - nettle=3.6=he412f7d_0
  - nodejs=14.17.4=h92b4a50_0
  - notebook=6.4.5=pyha770c72_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.72=hb5efdd6_0
  - numba=0.53.1=py39h56b8d98_1
  - numpy=1.19.5=py39hdbf815f_2
  - oauthlib=3.1.1=pyhd8ed1ab_0
  - olefile=0.46=pyh9f0ad1d_1
  - opencv=4.5.2=py39hf3d152e_1
  - openh264=2.1.1=h780b84a_0
  - openssl=1.1.1l=h7f98852_0
  - opt_einsum=3.3.0=pyhd8ed1ab_1
  - packaging=21.0=pyhd8ed1ab_0
  - palettable=3.3.0=py_0
  - pandas=1.2.5=py39hde0f152_0
  - pandoc=2.16.1=h7f98852_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.2=pyhd8ed1ab_0
  - patsy=0.5.2=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pip=21.2.4=py39h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - plotnine=0.8.0=pyhd8ed1ab_0
  - pooch=1.5.2=pyhd8ed1ab_0
  - prometheus_client=0.12.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.22=pyha770c72_0
  - protobuf=3.16.0=py39he80948d_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - py-opencv=4.5.2=py39hef51801_1
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.10.0=pyhd8ed1ab_0
  - pyjwt=2.3.0=pyhd8ed1ab_0
  - pylint=2.7.2=py39hf3d152e_0
  - pyopenssl=21.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.6=pyhd8ed1ab_0
  - pyqt=5.12.3=py39hf3d152e_8
  - pyqt-impl=5.12.3=py39hde8b62d_8
  - pyqt5-sip=4.19.18=py39he80948d_8
  - pyqtchart=5.12=py39h0fcd23e_8
  - pyqtwebengine=5.12.1=py39h0fcd23e_8
  - pyrsistent=0.18.0=py39heee7806_0
  - pysocks=1.7.1=py39hf3d152e_4
  - pysoundfile=0.10.3.post1=pyhd3deb0d_0
  - python=3.9.7=h12debd9_1
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-flatbuffers=1.12=pyhd8ed1ab_1
  - python_abi=3.9=2_cp39
  - pytorch=1.10.0=py3.9_cuda10.2_cudnn7.6.5_0
  - pytorch-mutex=1.0=cuda
  - pytz=2021.3=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyzmq=19.0.2=py39hb69f2a1_2
  - qt=5.12.9=hda022c4_4
  - re2=2021.09.01=h9c3ff4c_0
  - readline=8.1=h27cfd23_0
  - requests=2.26.0=pyhd8ed1ab_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - resampy=0.2.2=py_0
  - rsa=4.7.2=pyh44b312d_0
  - scikit-learn=0.24.2=py39h4dfa638_0
  - scipy=1.6.3=py39hee8e79c_0
  - seaborn=0.11.2=hd8ed1ab_0
  - seaborn-base=0.11.2=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=58.0.4=py39h06a4308_0
  - sip=4.19.13=py39h2531618_0
  - six=1.15.0=py_0
  - snappy=1.1.8=he6710b0_0
  - sniffio=1.2.0=py39hf3d152e_2
  - sqlite=3.36.0=hc218d9a_0
  - statsmodels=0.12.1=py39hce5d2b2_2
  - tensorboard=2.7.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.0=py39h3da14fd_0
  - tensorboard-plugin-wit=1.8.0=pyh44b312d_0
  - tensorflow-gpu=2.6.0=cuda102py39hf05f184_2
  - termcolor=1.1.0=py_2
  - terminado=0.12.1=py39hf3d152e_1
  - testpath=0.5.0=pyhd8ed1ab_0
  - threadpoolctl=3.0.0=pyh8a188c0_0
  - tk=8.6.11=h1ccaba5_0
  - toml=0.10.2=pyhd8ed1ab_0
  - torchaudio=0.10.0=py39_cu102
  - torchvision=0.11.1=py39_cu102
  - tornado=6.1=py39h3811e60_1
  - tqdm=4.62.3=pyhd8ed1ab_0
  - traitlets=5.1.1=pyhd8ed1ab_0
  - typing-extensions=3.7.4.3=0
  - typing_extensions=3.7.4.3=py_0
  - tzdata=2021e=hda174b7_0
  - urllib3=1.26.7=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.1.0=py39hf3d152e_1
  - werkzeug=2.0.1=pyhd8ed1ab_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - widgetsnbextension=3.5.2=py39hf3d152e_1
  - wrapt=1.12.1=py39h3811e60_3
  - x264=1!161.3030=h7f98852_1
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h7b6447c_0
  - yarl=1.6.3=py39h3811e60_2
  - zeromq=4.3.4=h9c3ff4c_0
  - zipp=3.6.0=pyhd8ed1ab_0
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - celluloid==0.2.0
    - click==7.1.2
    - colabcode==0.3.0
    - decorator==4.4.2
    - docker-pycreds==0.4.0
    - gitdb==4.0.9
    - gitpython==3.1.26
    - h11==0.12.0
    - h5py==2.10.0
    - jupyter-client==6.1.12
    - jupyterlab==3.0.7
    - keras==2.7.0
    - libclang==12.0.0
    - mpmath==1.2.1
    - nest-asyncio==1.4.3
    - noisereduce==2.0.0
    - pathtools==0.1.2
    - pillow==7.2.0
    - promise==2.3
    - psutil==5.9.0
    - pydot==1.4.2
    - pyngrok==5.1.0
    - pyyaml==6.0
    - sentry-sdk==1.5.4
    - shortuuid==1.0.8
    - smmap==5.0.0
    - sympy==1.9
    - tensorflow==2.7.0
    - tensorflow-estimator==2.7.0
    - tensorflow-io-gcs-filesystem==0.23.1
    - tifffile==2021.11.2
    - uvicorn==0.13.1
    - wandb==0.12.10
    - xgboost==1.5.1
    - yaspin==2.1.0
prefix: /net/store/cv/users/ybrima/miniconda3/envs/CV
